# Generated by Django 3.2.6 on 2022-04-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
