# Generated by Django 3.2.6 on 2022-05-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_recipe_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='rating_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
