# Generated by Django 3.2.6 on 2022-05-01 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220501_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='no_of_user_rated_points_1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='no_of_user_rated_points_2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='no_of_user_rated_points_3',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='no_of_user_rated_points_4',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='no_of_user_rated_points_5',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating_points_avg',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
