# Generated by Django 3.2.6 on 2022-05-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_favouriterecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
